FROM golang:1.17.3-alpine3.14 as builder

RUN apk add --no-cache \
    wget \
    make \
    git \
    gcc \
    binutils-gold \
    musl-dev

RUN mkdir -p /go/src/github.com/matrixorigin/mysql-tester

RUN git clone https://github.com/matrixorigin/mysql-tester.git /go/src/github.com/matrixorigin/mysql-tester

WORKDIR /go/src/github.com/matrixorigin/mysql-tester

RUN go mod download

RUN make build


FROM alpine

RUN apk add --no-cache bash

COPY --from=builder /go/src/github.com/matrixorigin/mysql-tester/mysql-tester /mysql-tester
COPY --from=builder /go/src/github.com/matrixorigin/mysql-tester/r /r
COPY  --from=builder /go/src/github.com/matrixorigin/mysql-tester/t /t

WORKDIR /

ENTRYPOINT ["/mysql-tester"]
